### ISSUE TITLE
Wishes

### ISSUE THREAD

**Issue by sjoerdvan** [alloy/macvim#17]
Really like the File drawer. Would love some settings.
- Always start with file drawer open
- Choose/have a standard side it opens to (I prefer right and can achieve this by making my Macvim screen larger to the left so it switches over)

I'll add some more when I remember

**Comment by sjoerdvan** [comment]
A couple of us here at work now use this a lot, and a colleague of mine patched the source so it now
-opens standard, 
-opens on the left side 
-doubled in size
We did the following changes in the code (respectively): (sorry, dont have GIT installed atm)
-In MMWindowController.m added above line 296 above return YES: [fileDrawerController open];
-In MMFileDrawerController.m added a line under 546 with [drawer openOnEdge:NSMinXEdge];
-In MMFileDrawerController.m on line 466 changed 200 to 400 (more of a preference)

Hope it helps, and for me Macvim with filedrawer rocks even more!

**Comment by b4winckler** [comment]
The side to open is determined by a user default.  To change it to the left, simply open Terminal and type

```
defaults write org.vim.MacVim MMDrawerPreferredEdge 1
```

Then restart MacVim.

**Comment by b4winckler** [comment]
I think all your wishes should be accommodated with the latest commits.  The width of the sidebar is autosaved (for first window opened), and there are now preferences (MacVim -> Preferences) to set whether the sidebar should open on startup and which side it should open up on.

**Comment by alloy** [comment]
Sweet.

**Comment by sjoerdvan** [comment]
Very nice, thank you!
