### ISSUE TITLE
Sidebar scroller covers window resize handler.

### ISSUE THREAD

**Issue by alloy** [alloy/macvim#19]
Disabling the scroller with:

```
set guioptions-=r
```

Results in the window resize handler being covered by the scroller in the sidebar, as can be seen in the following screenshot: http://www.cl.ly/3W3M2A2V1y2n2m2Y3I3x

**Comment by b4winckler** [comment]
I accidentally pushed this commit to the file-drawer branch.  I don't know if we should revert the commit on that branch.

In any case, I have pushed to the split-browser as well (where I should have pushed in the first place).

**Comment by alloy** [comment]
If I judge it correctly, it shouldn't have any negative impact, right? In which case I have no objection to it staying or reverting.

**Comment by b4winckler** [comment]
It seems like the file-drawer branch is the same as split-browser now?  If so the commit is harmless, but then why are we keeping the file-drawer branch around?

**Comment by alloy** [comment]
Oh wait, you probably pushed your local split-browser branch to the remote file-drawer branch, huh? In which case it now contains the same as the split-browser branch indeed… Hmm, I think the only way to fix that is to reset and force-push. I guess that shouldn't matter too much.

The idea was that the file-drawer branch would stay as it was so that people could still use that if they would run into serious bugs with the split-browser branch.

**Comment by b4winckler** [comment]
I mixed up the names "file-drawer" and "split-browser" so it is entirely possible I stuffed it up.  Do you mind resetting the "file-drawer" branch so that I don't make more mistakes. ;-)

Don't know where I went wrong, I am usually very careful about these things...

**Comment by alloy** [comment]
Done. No worries, nobody died :)
