### ISSUE TITLE
Window doesn't close

### ISSUE THREAD

**Issue by b4winckler** [alloy/macvim#21]
Trying to close a window results in results in

```
*** -[NSURL initFileURLWithPath:]: nil string parameter
```

being logged and the window never closes.

**Comment by alloy** [comment]
Fixed in b1ba22d1fc7173a54728f23692d7e851d96de69e

**Comment by b4winckler** [comment]
I forgot to thank you for fixing this so quickly. :-)

**Comment by alloy** [comment]
Oh, no problem, it was a simple fix :) But it’s good that you remind me, because I’m thinking we could now remove the BOOL ivar and simply check if the fileBrowser ivar isn't `nil`.

**Comment by b4winckler** [comment]
Ah yes, I was going to suggest that too but forgot. :-)

You may as well inherit from `NSObject` instead of `NSViewController` as well since none of the `NSViewController` features are really being used, but I guess that is a rather minor point...

**Comment by alloy** [comment]
And I forget it again :) Regarding inheriting from NSObject instead of NSViewController, there aren’t many features to begin with, I see it more as a hint of what kind of class it is.
