### ISSUE TITLE
Should we consider the source list style?

### ISSUE THREAD

**Issue by alloy** [alloy/macvim#22]
See: http://www.cl.ly/3P310N3T3R222f433i2x

**Comment by b4winckler** [comment]
I read the Apple HIG and I get the impression that a source list should only be used if it is the primary means of navigating the app (in some loose sense).  They also say that a source list should never be more than two levels deep.  All in all I get the impression that a source list for the file browser feature would go against the HIG, so I am inclined to say that we should _not_ use the source list style.

Maybe it would be nice if the background color adapted itself to the setting of the `bg` option however.  It is hard on the eyes with a white background in the file browser if you have a dark color scheme.  I'm not sure how it should be handled though.  We could try using the same background/foreground combination as is used by the text view, but I'm a bit dubious about this as well.  Perhaps we should just have two presets for dark/light and toggle between these two depending on what `bg` is set to?  Hmmm....I think I'm going off on a tangent here...

**Comment by alloy** [comment]
Ah, I quickly skimmed the HIG but didn’t see that text about source lists that you mention. My gut feeling was the same, but since people asked about it and I couldn't find it in the HIG I thought I’d make a note to investigate it more. So if the HIG mentions about it not going down more than two levels then we know enough, it's _not_ a thing we should do.

What do you mean by using the same bg/fg colors as the text view being ‘dubious’? Is it hard to get these values? Because I think we should simply try it and see how it works out to be able to really say anything about it. If that doesn't work out, then I agree we should at least provide two presets; for a light and a dark bg.

**Comment by b4winckler** [comment]
Hmmm...yes what did I mean by that?  My thoughts were something like:
-  the icons may blend in with the background color
-  I think (maybe) that the file browser should be visually distinct from the text view
-  background/foreground colors that look good for the text view may look bad for the file browser (this is basically the same as the first point)

I can't think of anything else right now.

If you want to try it out then you can get the background/foreground colors from `-[NSWindowController setDefaultColorsBackground:foreground:]` and simply pass those on to the file browser.  I'd like to try it out too if you write a patch.

**Comment by b4winckler** [comment]
Oh, here is the [HIG link to source lists](http://developer.apple.com/library/mac/#documentation/UserExperience/Conceptual/AppleHIGuidelines/XHIGWindows/XHIGWindows.html%23//apple_ref/doc/uid/20000961-CHDDIGDE).  I only read it very briefly a few weeks ago so it may be what I said earlier is not true.  Take a look yourself and see what you think.

**Comment by b4winckler** [comment]
My memory served me right, it clearly states that "A source list should not contain more than two levels of hierarchy", right under Figure 14-24.  So I'm still leaning towards not using the source list style.

**Comment by alloy** [comment]
Agreed, we’re not going to do this. I will create a new issue regarding the background/foreground colors of the text view.

**Comment by alloy** [comment]
Created new ticket regarding fg/bg colors: #23.
