### ISSUE TITLE
Backgroundcolor for filebrowser

### ISSUE THREAD

**Issue by robgietema** [alloy/macvim#24]
I really like the filebrowser in split view. What would be nice to have is to be able to set the background color for the file browser (or use the default Finder background color).

If you change the following around line 484 in MMFileBrowserController.m you get the default Finder color:

[fileBrowser setBackgroundColor:[NSColor colorWithCalibratedRed:0.874509803921569 green:0.894117647058824 blue:0.917647058823529 alpha:1]];
[pathControl setBackgroundColor:[NSColor colorWithCalibratedRed:0.874509803921569 green:0.894117647058824 blue:0.917647058823529 alpha:1]];

**Comment by alloy** [comment]
The better way to do this would be to change the [selection highlight style](http://developer.apple.com/library/mac/DOCUMENTATION/Cocoa/Reference/ApplicationKit/Classes/NSTableView_Class/Reference/Reference.html#//apple_ref/doc/c_ref/NSTableViewSelectionHighlightStyleSourceList). However, as discussed in #22, the source list style is not meant for lists like these.

There's also ticket #23 where we discussed about colors in general.

Right now the consensus is to not allow customization, but feel free to chime in on the existing discussions.
