### ISSUE TITLE
Possibility to reveal file in browser

### ISSUE THREAD

**Issue by shageman** [alloy/macvim#30]
I'd love to have the functionality to reveal the file currently in focus in the file browser (open all folders in the hierarchy above the file, highlight the file, and move browser to show file). Am I just not finding this option?

**Comment by alloy** [comment]
It’s the second to last item in the contextual menu: “Reveal Current File in File Browser”. If you have a suggestion for a better label, please shoot.

**Comment by shageman** [comment]
Ah, I see. I was looking for it in the context of the file. You get it when opening the context menu on the file browser.

The name is perfect. I was hoping for the possibility to set a keyboard shortcut for this in .gvimrc...

**Comment by datanoise** [comment]
`:macaction selectInDrawer:` used to do that, we should probably add something like `:macaction revealInDrawer:`

**Comment by alloy** [comment]
Added in 110d9920513829219fbb32f91c74ff8629123a8f and also added it as an experiment to the contextual menu of the text view.

**Comment by shageman** [comment]
Awesome! Thanks
