### ISSUE TITLE
some characters can't be typed

### ISSUE THREAD

**Issue by khelben** [alloy/macvim#31]
I've built your split-browser branch like stated in the readme_mac.txt.

But when I want to enter the following characters (no matter which mode): 

```
[
{
}
]
```

they are swapped with other characters.

I've compiled the latest snapshot from b4winkler (snapshot 59) and with that version, I don't have any problem.

I hope this can be solved I really love the split-browser.

TIA

Christiaan

**Comment by b4winckler** [comment]
Have you tried one of the [prebuilt binaries](https://github.com/alloy/macvim/downloads)?

**Comment by khelben** [comment]
great! the prebuilt binary works, can you tell me how you've compiled this (which options etc)? Because I really want to know what causes this.

Thx for the tip.

**Comment by b4winckler** [comment]
Assuming you follow the [build instructions](https://github.com/b4winckler/macvim/wiki/Building) to the letter then it should go away if you "make clean" followed by another "make".

**Comment by khelben** [comment]
yep, doing "make clean" fixed it, thx for the help.
