### ISSUE TITLE
Doesn't run on 10.6.8

### ISSUE THREAD

**Issue by Industrial** [alloy/macvim#34]
Hi,

$ mvim
dyld: Library not loaded: /System/Library/Perl/5.12/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /Applications/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
Trace/BPT trap
$ /System/Library/P
Perl/              PodcastProducer/   PreferencePanes/   Printers/          PrivateFrameworks/ 
$ /System/Library/Perl/
5.10.0/ 5.8.9/  Extras/ lib/

Seems the perl version is hardlinked

**Comment by b4winckler** [comment]
You don't mention which MacVim build you are using, but yes, all external language interfaces are statically linked.  You'll have to [build MacVim yourself](https://github.com/b4winckler/macvim/wiki/Building) if your system version does not match the one the binary you are using was built against.
