### ISSUE TITLE
Missing chrome on start

### ISSUE THREAD

**Issue by peterhellberg** [alloy/macvim#36]
I’m not getting any window chrome when opening the latest build (**MacVim.020920111108.zip**)

The Zoom and Toggle Full Screen Mode works just fine though.
## System

OS X (Lion 10.7.1)
## Example

![Missin chrome](https://img.skitch.com/20110902-eb44iibdj3ni9jfthf63rijukj.medium.jpg)

**Comment by alloy** [comment]
So is the window actually too far up and did you manage to bring it down?

**Comment by peterhellberg** [comment]
The window doesn’t have any chrome at all until I select the Window/Zoom menu option.

## Edit:

Scratch that, the window chrome is there. It is just hidden behind the menu bar.

My resolution is 1366x768 (Air 11.6")

**Comment by alloy** [comment]
Ok gotcha, thanks for the followup.

**Comment by peterhellberg** [comment]
I’m able to reset the window position with:

```
au GUIEnter * winpos 0 1
```

**Comment by b4winckler** [comment]
Hmmm...I think `-[MMWindow constrainFrameRect:toScreen:]` is to blame.  I will check it out.

**Comment by peterhellberg** [comment]
Thank you guys :)

**Comment by alloy** [comment]
Nice, thanks @b4winckler
