### ISSUE TITLE
Terminal.app

### ISSUE THREAD

**Issue by DAddYE** [alloy/macvim#37]
There is the possibility to add the terminal inside macvim? I really don't like external plugins like conque-term etc...

Thanks!

**Comment by alloy** [comment]
I have no idea, there are probably ways to do :)

However, this MacVim fork is about the file browser side bar, not MacVim in general. Since this also isn’t a real ‘issue’, you should probably ask this on the vim mailing lists, irc channel, stackoverflow.com, etc.

HTH
