### ISSUE TITLE
Unable to build on OSX Lion?

### ISSUE THREAD

**Issue by joneilloine** [alloy/macvim#43]
I'm trying to follow the installation instructions, but I'm getting an error on 'make' that I've not been able to get past. Just hoping you may have insights. I have the latest Xcode beta installed (Xcode 4.2 Developer Preview 7) ... could that be the problem?

[~/Development/GitHub]$ git clone git://github.com/alloy/macvim.git
[~/Development/GitHub]$ cd macvim/src
[~/Development/GitHub/macvim/src]$ ./configure --with-features=huge \
[~/Development/GitHub/macvim/src]>                   --enable-rubyinterp \
[~/Development/GitHub/macvim/src]>                   --enable-pythoninterp \
[~/Development/GitHub/macvim/src]>                   --enable-perlinterp \
[~/Development/GitHub/macvim/src]>                   --enable-cscope
...
...
...
configure: creating ./config.status
config.status: creating auto/config.mk
config.status: creating auto/config.h
[~/Development/GitHub/macvim/src]$ make
...
...
...
2011-09-12 10:09:10.418 xcodebuild[22234:4403] error: Error Domain=NSPOSIXErrorDomain Code=2 "Non-zero exit code 127 returned from shell command: /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x objective-c -c /dev/null 2>&1" UserInfo=0x400958d00 {NSLocalizedDescription=Non-zero exit code 127 returned from shell command: /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x objective-c -c /dev/null 2>&1, NSLocalizedFailureReason=No such file or directory}
2011-09-12 10:09:10.419 xcodebuild[22234:4403] Warning:  Couldn't discover the 'gcc-4.2' compiler's built-in search paths and preprocessor definitions for language dialect 'objective-c'.
Compiler: /Developer/usr/bin/gcc-4.2
Reason:   /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x objective-c -c /dev/null 2>&1
2011-09-12 10:09:10.466 xcodebuild[22234:4403] error: Error Domain=NSPOSIXErrorDomain Code=22 "Non-zero exit code 127 returned from shell command: /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x c -c /dev/null 2>&1" UserInfo=0x4007abd20 {NSLocalizedDescription=Non-zero exit code 127 returned from shell command: /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x c -c /dev/null 2>&1, NSLocalizedFailureReason=Invalid argument}
2011-09-12 10:09:10.467 xcodebuild[22234:4403] Warning:  Couldn't discover the 'gcc-4.2' compiler's built-in search paths and preprocessor definitions for language dialect 'c'.
Compiler: /Developer/usr/bin/gcc-4.2
Reason:   /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x c -c /dev/null 2>&1
=== BUILD NATIVE TARGET PSMTabBarControlFramework OF PROJECT PSMTabBarControl WITH THE DEFAULT CONFIGURATION (Release) ===
Check dependencies
Unsupported compiler 'GCC 4.2' selected for architecture 'x86_64'

*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
make: **\* [macvim] Error 65
[~/Development/GitHub/macvim/src]$

**Comment by alloy** [comment]
I haven't tried to build it with the Xcode preview and haven't had any problems building on Lion with the released version. So yeah, I’m going to assume that's the problem. Anyways, do you still have /usr/bin/gcc-4.0 ? If so, maybe try something like:

```
$ env CC=gcc-4.0 ./configure […the rest…]
$ make
```

**Comment by wjlafrance** [comment]
I've replicated joneilloine's issue, and with the env set, I get the same issue with a different flavor:

[11:23:01] [william@enterprise ~/dev/macvim]$ env CC=gcc-4.0
rvm_gemsets_path=/Users/william/.rvm/gemsets
rvm_dump_environment_flag=0
rvm_scripts_path=/Users/william/.rvm/scripts
rvm_bin_path=/Users/william/.rvm/bin
TERM_PROGRAM=Apple_Terminal
rvm_clang_flag=0
rvm_archive_extension=tar.bz2
GEM_HOME=/Users/william/.rvm/gems/ruby-1.9.2-p290
rvm_man_path=/Users/william/.rvm/man
TERM=xterm-256color
SHELL=/bin/bash
IRBRC=/Users/william/.rvm/rubies/ruby-1.9.2-p290/.irbrc
TMPDIR=/var/folders/jj/rs1s4lv109544w1qmfxn9rvr0000gn/T/
rvm_user_path=/Users/william/.rvm/user
Apple_PubSub_Socket_Render=/tmp/launch-f90pFD/Render
rvm_wrappers_path=/Users/william/.rvm/wrappers
TERM_PROGRAM_VERSION=299
rvm_patches_path=/Users/william/.rvm/patches
OLDPWD=/Users/william/dev
rvm_docs_path=/Users/william/.rvm/docs
MY_RUBY_HOME=/Users/william/.rvm/rubies/ruby-1.9.2-p290
TERM_SESSION_ID=6AD5FB31-81E1-45D1-94F8-0FAE6A35CD47
rvm_verbose_flag=1
USER=william
rvm_gems_cache_path=/Users/william/.rvm/gems/cache
COMMAND_MODE=unix2003
rvm_path=/Users/william/.rvm
rvm_debug_flag=0
SSH_AUTH_SOCK=/tmp/launch-E9K6fd/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0:0
rvm_ruby_global_gems_path=/Users/william/.rvm/gems/ruby-1.9.2-p290@global
rvm_prefix=/Users/william
rvm_examples_path=/Users/william/.rvm/examples
PATH=/Users/william/.rvm/gems/ruby-1.9.2-p290/bin:/Users/william/.rvm/gems/ruby-1.9.2-p290@global/bin:/Users/william/.rvm/rubies/ruby-1.9.2-p290/bin:/Users/william/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
rvm_rubies_path=/Users/william/.rvm/rubies
PWD=/Users/william/dev/macvim
LANG=en_US.UTF-8
rvm_usr_path=/Users/william/.rvm/usr
PS1=[\t] [\u@\h \w]$ 
rvm_src_path=/Users/william/.rvm/src
rvm_version=1.8.0
SHLVL=1
HOME=/Users/william
rvm_gems_path=/Users/william/.rvm/gems
rvm_ruby_string=ruby-1.9.2-p290
rvm_tmp_path=/Users/william/.rvm/tmp
LOGNAME=william
rvm_lib_path=/Users/william/.rvm/lib
GEM_PATH=/Users/william/.rvm/gems/ruby-1.9.2-p290:/Users/william/.rvm/gems/ruby-1.9.2-p290@global
rvm_repos_path=/Users/william/.rvm/repos
rvm_log_path=/Users/william/.rvm/log
rvm_reload_flag=0
rvm_help_path=/Users/william/.rvm/help
rvm_delete_flag=0
DISPLAY=/tmp/launch-TUf2zN/org.x:0
rvm_environments_path=/Users/william/.rvm/environments
rvm_archives_path=/Users/william/.rvm/archives
RUBY_VERSION=ruby-1.9.2-p290
SECURITYSESSIONID=186b6
rvm_user_install_flag=1
_=/usr/bin/env
CC=gcc-4.0
[11:28:36] [william@enterprise ~/dev/macvim]$ ./configure
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for library containing strerror... none required
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking for strip... strip
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
configure: checking for buggy tools...
- sh is 'GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin11)
  Copyright (C) 2007 Free Software Foundation, Inc.' - probably OK.
  checking for BeOS... no
  checking for QNX... no
  checking for Darwin (Mac OS X)... yes
  checking --disable-darwin argument... no
  checking if Darwin files are there... yes
  checking --with-developer-dir argument... not present
  checking for xcode-select... /usr/bin/xcode-select
  checking for developer dir using xcode-select... /Developer
  checking --with-macsdk argument... using default
  checking --with-macarchs argument... defaulting to native arch
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking Carbon/Carbon.h usability... yes
  checking Carbon/Carbon.h presence... yes
  checking for Carbon/Carbon.h... yes
  checking Cocoa/Cocoa.h usability... yes
  checking Cocoa/Cocoa.h presence... yes
  checking for Cocoa/Cocoa.h... yes
  checking --with-local-dir argument... Defaulting to /usr/local
  checking --with-vim-name argument... Defaulting to vim
  checking --with-ex-name argument... Defaulting to ex
  checking --with-view-name argument... Defaulting to view
  checking --with-global-runtime argument... no
  checking --with-modified-by argument... no
  checking if character set is EBCDIC... no
  checking --disable-selinux argument... no
  checking for is_selinux_enabled in -lselinux... no
  checking --with-features argument... Defaulting to normal
  checking --with-compiledby argument... no
  checking --disable-xsmp argument... no
  checking --disable-xsmp-interact argument... no
  checking --enable-luainterp argument... no
  checking --enable-mzschemeinterp argument... no
  checking --enable-perlinterp argument... no
  checking --enable-pythoninterp argument... no
  checking --enable-python3interp argument... no
  checking --enable-tclinterp argument... no
  checking --enable-rubyinterp argument... no
  checking --enable-cscope argument... no
  checking --enable-workshop argument... no
  checking --disable-netbeans argument... no
  checking for socket in -lsocket... no
  checking for gethostbyname in -lnsl... no
  checking whether compiling netbeans integration is possible... yes
  checking --enable-sniff argument... no
  checking --enable-multibyte argument... no
  checking --enable-hangulinput argument... no
  checking --enable-xim argument... defaulting to auto
  checking --enable-fontset argument... no
  defaulting to: don't HAVE_X11
  checking --enable-gui argument... yes/auto - automatic GUI support
  checking whether or not to look for MacVim... yes
  checking for MacVim GUI... yes
  checking X11/SM/SMlib.h usability... yes
  checking X11/SM/SMlib.h presence... yes
  checking for X11/SM/SMlib.h... yes
  checking whether toupper is broken... no
  checking whether **DATE** and **TIME** work... yes
  checking whether **attribute**((unused)) is allowed... yes
  checking elf.h usability... no
  checking elf.h presence... no
  checking for elf.h... no
  checking for dirent.h that defines DIR... yes
  checking for library containing opendir... none required
  checking stdarg.h usability... yes
  checking stdarg.h presence... yes
  checking for stdarg.h... yes
  checking for stdint.h... (cached) yes
  checking for stdlib.h... (cached) yes
  checking for string.h... (cached) yes
  checking sys/select.h usability... yes
  checking sys/select.h presence... yes
  checking for sys/select.h... yes
  checking sys/utsname.h usability... yes
  checking sys/utsname.h presence... yes
  checking for sys/utsname.h... yes
  checking termcap.h usability... yes
  checking termcap.h presence... yes
  checking for termcap.h... yes
  checking fcntl.h usability... yes
  checking fcntl.h presence... yes
  checking for fcntl.h... yes
  checking sgtty.h usability... yes
  checking sgtty.h presence... yes
  checking for sgtty.h... yes
  checking sys/ioctl.h usability... yes
  checking sys/ioctl.h presence... yes
  checking for sys/ioctl.h... yes
  checking sys/time.h usability... yes
  checking sys/time.h presence... yes
  checking for sys/time.h... yes
  checking for sys/types.h... (cached) yes
  checking termio.h usability... no
  checking termio.h presence... no
  checking for termio.h... no
  checking iconv.h usability... yes
  checking iconv.h presence... yes
  checking for iconv.h... yes
  checking for inttypes.h... (cached) yes
  checking langinfo.h usability... yes
  checking langinfo.h presence... yes
  checking for langinfo.h... yes
  checking math.h usability... yes
  checking math.h presence... yes
  checking for math.h... yes
  checking for unistd.h... (cached) yes
  checking stropts.h usability... no
  checking stropts.h presence... no
  checking for stropts.h... no
  checking errno.h usability... yes
  checking errno.h presence... yes
  checking for errno.h... yes
  checking sys/resource.h usability... yes
  checking sys/resource.h presence... yes
  checking for sys/resource.h... yes
  checking sys/systeminfo.h usability... no
  checking sys/systeminfo.h presence... no
  checking for sys/systeminfo.h... no
  checking locale.h usability... yes
  checking locale.h presence... yes
  checking for locale.h... yes
  checking sys/stream.h usability... no
  checking sys/stream.h presence... no
  checking for sys/stream.h... no
  checking termios.h usability... yes
  checking termios.h presence... yes
  checking for termios.h... yes
  checking libc.h usability... yes
  checking libc.h presence... yes
  checking for libc.h... yes
  checking sys/statfs.h usability... no
  checking sys/statfs.h presence... no
  checking for sys/statfs.h... no
  checking poll.h usability... yes
  checking poll.h presence... yes
  checking for poll.h... yes
  checking sys/poll.h usability... yes
  checking sys/poll.h presence... yes
  checking for sys/poll.h... yes
  checking pwd.h usability... yes
  checking pwd.h presence... yes
  checking for pwd.h... yes
  checking utime.h usability... yes
  checking utime.h presence... yes
  checking for utime.h... yes
  checking sys/param.h usability... yes
  checking sys/param.h presence... yes
  checking for sys/param.h... yes
  checking libintl.h usability... no
  checking libintl.h presence... no
  checking for libintl.h... no
  checking libgen.h usability... yes
  checking libgen.h presence... yes
  checking for libgen.h... yes
  checking util/debug.h usability... no
  checking util/debug.h presence... no
  checking for util/debug.h... no
  checking util/msg18n.h usability... no
  checking util/msg18n.h presence... no
  checking for util/msg18n.h... no
  checking frame.h usability... no
  checking frame.h presence... no
  checking for frame.h... no
  checking sys/acl.h usability... yes
  checking sys/acl.h presence... yes
  checking for sys/acl.h... yes
  checking sys/access.h usability... no
  checking sys/access.h presence... no
  checking for sys/access.h... no
  checking sys/sysinfo.h usability... no
  checking sys/sysinfo.h presence... no
  checking for sys/sysinfo.h... no
  checking wchar.h usability... yes
  checking wchar.h presence... yes
  checking for wchar.h... yes
  checking wctype.h usability... yes
  checking wctype.h presence... yes
  checking for wctype.h... yes
  checking for sys/ptem.h... no
  checking for sys/sysctl.h... yes
  checking for pthread_np.h... no
  checking for strings.h... (cached) yes
  checking whether gcc needs -traditional... no
  checking for an ANSI C-conforming const... yes
  checking for working volatile... yes
  checking for mode_t... yes
  checking for off_t... yes
  checking for pid_t... yes
  checking for size_t... yes
  checking for uid_t in sys/types.h... yes
  checking for uint32_t... yes
  checking whether time.h and sys/time.h may both be included... yes
  checking for ino_t... yes
  checking for dev_t... yes
  checking whether byte ordering is bigendian... no
  checking for rlim_t... yes
  checking for stack_t... yes
  checking whether stack_t has an ss_base field... no
  checking --with-tlib argument... empty: automatic terminal library selection
  checking for tgetent in -ltinfo... no
  checking for tgetent in -lncurses... yes
  checking whether we talk terminfo... yes
  checking what tgetent() returns for an unknown terminal... non-zero
  checking whether termcap.h contains ospeed... yes
  checking whether termcap.h contains UP, BC and PC... yes
  checking whether tputs() uses outfuntype... no
  checking whether sys/select.h and sys/time.h may both be included... yes
  checking for /dev/ptc... no
  checking for SVR4 ptys... yes
  checking for ptyranges... pqrstuvw / 0123456789abcdef
  checking default tty permissions/group... can't determine - assume ptys are world accessible
  world
  checking return type of signal handlers... void
  checking for struct sigcontext... yes
  checking getcwd implementation is broken... no
  checking for bcmp... yes
  checking for fchdir... yes
  checking for fchown... yes
  checking for fsync... yes
  checking for getcwd... yes
  checking for getpseudotty... no
  checking for getpwnam... yes
  checking for getpwuid... yes
  checking for getrlimit... yes
  checking for gettimeofday... yes
  checking for getwd... yes
  checking for lstat... yes
  checking for memcmp... yes
  checking for memset... yes
  checking for mkdtemp... yes
  checking for nanosleep... yes
  checking for opendir... yes
  checking for putenv... yes
  checking for qsort... yes
  checking for readlink... yes
  checking for select... yes
  checking for setenv... yes
  checking for setpgid... yes
  checking for setsid... yes
  checking for sigaltstack... yes
  checking for sigstack... no
  checking for sigset... yes
  checking for sigsetjmp... yes
  checking for sigaction... yes
  checking for sigvec... yes
  checking for strcasecmp... yes
  checking for strerror... yes
  checking for strftime... yes
  checking for stricmp... no
  checking for strncasecmp... yes
  checking for strnicmp... no
  checking for strpbrk... yes
  checking for strtol... yes
  checking for tgetent... yes
  checking for towlower... yes
  checking for towupper... yes
  checking for iswupper... yes
  checking for usleep... yes
  checking for utime... yes
  checking for utimes... yes
  checking for _LARGEFILE_SOURCE value needed for large files... no
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... no
  checking for st_blksize... yes
  checking whether stat() ignores a trailing slash... no
  checking for iconv_open()... yes; with -liconv
  checking for nl_langinfo(CODESET)... yes
  checking for strtod in -lm... yes
  checking for strtod() and other floating point functions... yes
  checking --disable-acl argument... no
  checking for acl_get_file in -lposix1e... no
  checking for acl_get_file in -lacl... no
  checking for POSIX ACL support... yes
  checking for Solaris ACL support... no
  checking for AIX ACL support... no
  checking --disable-gpm argument... no
  checking for gpm... no
  checking --disable-sysmouse argument... no
  checking for sysmouse... no
  checking for FD_CLOEXEC... yes
  checking for rename... yes
  checking for sysctl... yes
  checking for sysinfo... not usable
  checking for sysinfo.mem_unit... no
  checking for sysconf... not usable
  checking for int... yes
  checking size of int... 4
  checking for long... yes
  checking size of long... 8
  checking for time_t... yes
  checking size of time_t... 8
  checking for off_t... (cached) yes
  checking size of off_t... 8
  checking uint32_t is 32 bits... ok
  checking whether memmove handles overlaps... yes
  checking for _xpg4_setrunelocale in -lxpg4... no
  checking how to create tags... ctags -t
  checking how to run man with a section nr... man -s
  checking --disable-nls argument... no
  checking for msgfmt... no
  checking for NLS... msgfmt not found - disabled
  checking dlfcn.h usability... yes
  checking dlfcn.h presence... yes
  checking for dlfcn.h... yes
  checking for dlopen()... yes
  checking for dlsym()... yes
  checking setjmp.h usability... yes
  checking setjmp.h presence... yes
  checking for setjmp.h... yes
  checking whether we need -framework Cocoa... yes
  checking --with-xcodecfg argument... using default
  checking for GCC 3 or later... yes
  checking whether we need -D_FORTIFY_SOURCE=1... yes
  checking linker --as-needed support... no
  configure: creating ./config.status
  config.status: creating auto/config.mk
  config.status: creating auto/config.h
  config.status: auto/config.h is unchanged
  [11:28:57] [william@enterprise ~/dev/macvim]$ make
  Starting make in the src directory.
  If there are problems, cd to the src directory and run make there
  cd src && make first
  creating auto/pathdef.c
  gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX -no-cpp-precomp  -g -O2 -D_FORTIFY_SOURCE=1       -o objects/pathdef.o auto/pathdef.c
  gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX -no-cpp-precomp  -g -O2 -D_FORTIFY_SOURCE=1       version.c -o objects/version.o
  link.sh: The file 'auto/link.sed' exists, which is going to be used now.
  link.sh: If linking fails, try deleting the auto/link.sed file.
  link.sh: If this fails too, try creating an empty auto/link.sed file.
  link.sh: Using unmodified link command
  gcc       -o Vim objects/buffer.o objects/blowfish.o objects/charset.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/mark.o objects/memline.o objects/menu.o objects/message.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/syntax.o  objects/tag.o objects/term.o objects/ui.o objects/undo.o objects/version.o objects/window.o objects/gui.o objects/gui_beval.o objects/pty.o objects/gui_macvim.o objects/MMBackend.o objects/MacVim.o        objects/os_macosx.o objects/os_mac_conv.o  objects/netbeans.o  objects/main.o objects/memfile.o -framework Cocoa -framework Carbon      -lm -lncurses  -liconv -framework Cocoa  
  link.sh: Linked OK
  xcodebuild -project MacVim/MacVim.xcodeproj 
  === BUILD NATIVE TARGET PSMTabBarControlFramework OF PROJECT PSMTabBarControl WITH THE DEFAULT CONFIGURATION (Release) ===
  Check dependencies
  2011-09-12 11:29:48.731 xcodebuild[14387:8f03] error: Error Domain=NSPOSIXErrorDomain Code=2 "Non-zero exit code 127 returned from shell command: /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x objective-c -c /dev/null 2>&1" UserInfo=0x40151ee80 {NSLocalizedDescription=Non-zero exit code 127 returned from shell command: /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x objective-c -c /dev/null 2>&1, NSLocalizedFailureReason=No such file or directory}
  2011-09-12 11:29:48.732 xcodebuild[14387:8f03] Warning:  Couldn't discover the 'gcc-4.2' compiler's built-in search paths and preprocessor definitions for language dialect 'objective-c'.
  Compiler: /Developer/usr/bin/gcc-4.2
  Reason:   /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x objective-c -c /dev/null 2>&1
  2011-09-12 11:29:48.791 xcodebuild[14387:8f03] error: Error Domain=NSPOSIXErrorDomain Code=22 "Non-zero exit code 127 returned from shell command: /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x c -c /dev/null 2>&1" UserInfo=0x400e45b00 {NSLocalizedDescription=Non-zero exit code 127 returned from shell command: /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x c -c /dev/null 2>&1, NSLocalizedFailureReason=Invalid argument}
  2011-09-12 11:29:48.791 xcodebuild[14387:8f03] Warning:  Couldn't discover the 'gcc-4.2' compiler's built-in search paths and preprocessor definitions for language dialect 'c'.
  Compiler: /Developer/usr/bin/gcc-4.2
  Reason:   /Developer/usr/bin/gcc-4.2 -v -E -dM -arch x86_64 -x c -c /dev/null 2>&1
  Unsupported compiler 'GCC 4.2' selected for architecture 'x86_64'

*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
make[1]: **\* [macvim] Error 65
make: **\* [first] Error 2
[11:29:49] [william@enterprise ~/dev/macvim]$

**Comment by joneilloine** [comment]
I downgraded to the non-beta version of Xcode and it worked fine, so looks like there will be some issues to deal with when the next version of Xcode is released, but I'm in business. Thanks for the quick investigation and response!

**Comment by alloy** [comment]
Thanks for the response, I'll have to try with a preview in the near future.

I forgot to say this in my first response, but the latest build (available from the downloads section) has been built for Lion, in case you don't want install the released version of Xcode.
