### ISSUE TITLE
File sorting problem under network volumes

### ISSUE THREAD

**Issue by sevein** [alloy/macvim#44]
For some reason, contents of network volumes are not shown in alphabetic order.

Please, see this screenshot: http://i52.tinypic.com/mr33p2.png

**Comment by alloy** [comment]
Thanks for the report!

When testing on local shares I already got sorted results, so could you please build the current version and check that it actually works as expected?

**Comment by sevein** [comment]
It is working now. Thank you!

**Comment by alloy** [comment]
Thanks for verifying.
