### ISSUE TITLE
Directories on top

### ISSUE THREAD

**Issue by honza** [alloy/macvim#45]
Is there a way to show directories on top and then files? Thanks

**Comment by alloy** [comment]
Nope sorry, because that’s not what the OS X way is.

**Comment by sc68cal** [comment]
I beg to differ - 
![Xfile](http://i.imgur.com/m4JOq.png)

**Comment by honza** [comment]
I was unaware. I shall submit to the ways of the great Mac OSX.

**Comment by alloy** [comment]
@sc68cal By which I mean the default behavior of the Finder and file panels etc, not a third party tool. Also note that this has nothing to do with if _I_ would prefer the one over the other personally, I have no strong feeling for the one over the other, but doing what the standard of the platform is.

**Comment by sc68cal** [comment]
You are still incorrect. Finder and file panels can still sort by "Kind" which groups directories together near the top.You really don't understand what the "standard of the platform is", so please stop using it as an excuse to close issues. 

More to the point: If someone were to go out and make a patch that does this, would you refuse to accept it?

**Comment by sc68cal** [comment]
[Here's a trivial example of how to accomplish this](https://gist.github.com/1248652).

Note that I skip using NSFileManager because currently your code grinds to a halt in large directories, notably expanding /usr/share/man

**Comment by alloy** [comment]
> You are still incorrect. Finder and file panels can still sort by "Kind" which groups directories together near the top.

Let me get this straight. You are saying that I’m incorrect in that “the default behavior is to not sort by kind” and then you justify that by saying that it can be achieved by telling me that you can deviate from the default behavior? Do you understand the meaning of “default behavior”? That was a rhetorical question, you apparently don’t.

> You really don't understand what the "standard of the platform is", so please stop using it as an excuse to close issues.

Three things: First, I don’t owe you shit, so if I decide to close an issue I will. Second, I understand what I said and mean, you don’t, see above, Third, ‘issues’ is the plural form, this is one ticket, I guess you thought that exaggerating your point would make it more worth, but it’s still worthless.

> More to the point: If someone were to go out and make a patch that does this, would you refuse to accept it?

Feel free to create a patch, I have never said anything about not accepting it. But one hint, a ‘trivial example’ has nothing to do with design, which is where most time is spent, implementing just the sorting is something anyone can do.

Unless you decide to _not_ be a douchebag, I have no intent on continuing any discussion with you. Learn some social skills.

**Comment by simonwhitaker** [comment]
I would like to see files ordered by the primary colour of their icons, in rainbow order, with a unicorn leaping through them.

But I expect you're going to say that this is "not the OS X way", either. That's lame.

**Comment by Pewpewarrows** [comment]
Why not provide an option to show directories first?

**Comment by alloy** [comment]
If someone creates a patch that does that and has an option in, for instance, the contextual menu, then I will apply it.
