### ISSUE TITLE
Add option to list folders at top

### ISSUE THREAD

**Issue by stanlemon** [alloy/macvim#52]
Add an option which would allow folders to appear grouped together at the top of a tree above any files in the containing folder.  This makes it easier to navigate and drill down into folders.

**Comment by alloy** [comment]
If someone (you?) provides a patch that does this and adds the toggle option to the contextual menu, then I will gladly apply it. But since I don't need it _and_ it’s not the default sort used in, for instance, the Finder, I won't implement it. Sorry.

**Comment by stanlemon** [comment]
What about doing it for a bounty or a donation?  

## 
- Stan Lemon
  stosh1985@gmail.com

**Comment by alloy** [comment]
Hmm, maybe. Did you have anything concrete in mind? :)

**Comment by stanlemon** [comment]
I don't know what the effort is an admittedly I don't have a lot of
money but I would without a doubt pay $20 or so. I'm not sure if
that's palatable to you or not, but I am very interested in the
feature and I think others might be as well. As a whole, you might
want to consider setting up PayPal donations for your fork. I know I
would have already made a donation at this point, macvim with a
sidebar is just awesome.

Sent from my iPhone

On Dec 20, 2011, at 9:49 AM, "Eloy Durán"
reply@reply.github.com
wrote:

**Comment by alloy** [comment]
Well, I don’t really want to receive ‘money’ donations in either case. I just create what I need, if others find it useful than that’s an added benefit :)

I do like to receive random small gifts, though! It’s the thought that counts for me :) Alas, I haven't created an up-to-date wish list for quite a while…

Anyways, I’ll just take a look at how much work this is, somewhere this week, and if it’s not much and I have the time I will add it.

**Comment by stanlemon** [comment]
I appreciate that and please do send me a wish list when you have one and it's updated.  I really do appreciate the work you've put into this!

**Comment by levifig** [comment]
I'd love to know the state of this… Lack of folders on top is one of my biggest annoyances with Finder (right there next to file loss bugs) and I can't see a good reason for the lack of that option.

Also, us developers many times work in directories with a bunch of files and changing the working directory all the time is kind of annoying… :)
