### ISSUE TITLE
strange crash on OSX 10.7.3

### ISSUE THREAD

**Issue by kaosbeat** [alloy/macvim#54]
fresh macbookpro, with fresh git clone (and https://github.com/carlhuda/janus .vimrc)
if I launch MacVim from commandline I get:

```
#:~ kaos$ mvim .
#:~ kaos$ Vim(41206,0x7fff72a72960) malloc: *** error for object 0x7fe300000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Vim: Caught deadly signal ABRT
```

CPU goes to 100% and I have to kill vim. The text window is never editable, just empty

**Comment by alloy** [comment]
Does it happen with an empty vimrc too?

If not, please find the exact line of config code that triggers this.

**Comment by b4winckler** [comment]
Also: @kaosbeat if you have further questions/problems please take this discussion to the vim_mac Google group -- this issue tracker does not track general Vim or MacVim problems.

**Comment by kaosbeat** [comment]
It happens on empty .vimrc/.vim/.viminfo too now trying drawerless macvim, and continuing here http://groups.google.com/group/vim_mac?pli=1

**Comment by kjyv** [comment]
Closing since it was an upstream issue
