### ISSUE TITLE
Unable to use Command-T w/ alloy's MacVim

### ISSUE THREAD

**Issue by steadystatic** [alloy/macvim#57]
I think command t might be mapped to something initially because I get:

:call <SNR>45_LaunchPeepOpenViaVim() in the vim command prompt when attempting ⌘+t.

I tried to install the Vimball of Command-T but something in the build makes it incompatible it seems like. Anyone else experience this and have a fix?

**Comment by alloy** [comment]
It looks like you’ve installed the PeepOpen plugin in the past, please check your configs. I’m pretty sure this is **not** a getting that comes with the source of MacVim.

**Comment by steadystatic** [comment]
OK – I'll check my configs. Thanks for the tip! Could be the fork of Janus I'm using.

**Comment by alloy** [comment]
Oh yeah, that could very well be the case. No problem :)
