### ISSUE TITLE
shortcut to move between the file browser and the file content ?

### ISSUE THREAD

**Issue by ahmadseleem** [alloy/macvim#59]
shortcut to move between the file browser and the file content ?

**Comment by sheam** [comment]
+1 for this.

I have to say, just discovered this, and this build + peep open have made me forget about Sublime Text 2.

**Comment by gicappa** [comment]
+1 I'd need this too. The project is great! Thanks

**Comment by alloy** [comment]
Do the options in https://github.com/alloy/macvim/wiki/Usage not suffice for you?

**Comment by gicappa** [comment]
Yeps. Sorry I missed it. Thanks
