### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by henrymazza** [alloy/macvim#61]
The split-panel version has a serious memory leak problem: 

[Memory Comparison](http://henrymazza.s3.amazonaws.com/Screen%20Shot%202012-08-09%20at%2012.12.36.png)

Using actual Homebrew version.

**Comment by alloy** [comment]
It might also be an issue with the version that this fork is based on. The one in homebrew is no doubt a newer version. I hope to get to some updating and maintenance soon, but I can’t promise anything.

**Comment by henrymazza** [comment]
With what is it based on? The file drawer branch? Or the Macvim build itself?

What version you use personally? Does it have any memory issue? The versions I used to comparison:

Macbrew: https://github.com/alloy/macvim/tarball/1167a32988202c3c81842371ecf9f80fe4854172  (version '20120109')

MacVim: https://github.com/downloads/b4winckler/macvim/MacVim-snapshot-64.tbz  (Released Jan 2, 2012.)

**Comment by alloy** [comment]
> With what is it based on? The file drawer branch? Or the Macvim build itself?

I don’t completely follow what you mean, but the last upstream commit in this repo is 54b2b3cf5e39b12181d2ede9cc49f5601a5ffaba.

> What version you use personally? Does it have any memory issue?

I can confirm that the memory usage is too high here as well.

**Comment by henrymazza** [comment]
I was trying to understand what "issue with the fork" means.

**Comment by alloy** [comment]
Based on your comparison I think it’s safe to say that the issue is not with that version of upstream MacVim, but with file drawer specific code. Anyway, I’ll take a look asap, it shouldn't be hard to find the cause.

**Comment by henrymazza** [comment]
Never had any more problems with this as of 10e7bedcdb and OS X 10.8.3. Closing.
