### ISSUE TITLE
Command-line switch to enable or disable the sidebar

### ISSUE THREAD

**Issue by tubbo** [alloy/macvim#64]
I use MacVim for both general editing and as my `git mergetool` for diffing and resolving conflicts.

It would be really nice if I didn't have to Cmd+Shift+D every time I opened up `mvimdiff` and it would just hide the sidebar for me. Generally, diffing takes up so much of the window that the sidebar just makes everything harder to see.

Is there currently a way to do this? I was thinking of something like `mvim -s` to invoke the sidebar. That way I can leave the sidebar off by default, and just open any projects I want the sidebar on with `mvim -s .`

**Comment by alloy** [comment]
There currently is no way to do this and I would rather not touch the CLI part of the codebase, as it makes it that much harder to maintain from upstream.

What might be an option, though, is to check for an env var, would that work for you?

**Comment by markus** [comment]
People who use mvim frequently without the sidebar could set up a shell alias:

alias myvim='MVIM_SIDEBAR=off mvim'

**Comment by tubbo** [comment]
@alloy yeah that works, definitely. whatever's easiest to integrate with upstream.
