### ISSUE TITLE
Cannot open any windows

### ISSUE THREAD

**Issue by jordwalke** [alloy/macvim#68]
MacVim starts up and no windows open. I can press CMD-n which does nothing at all - until I close the application, is asks if I want to close all of the windows that I "opened". The menu-bar "Window" menu does not list any of them. It's completely unusable, obviously. Still occurs with an empty vimrc.

**Comment by jordwalke** [comment]
Can anyone verify a repro?

**Comment by b4winckler** [comment]
This sometimes happens when people compile from sources themselves.  Try a prebuilt binary, or it may be that you simply need to build with `CC=clang ./configure`, then `make`.

**Comment by jordwalke** [comment]
I see - I think it was the `CC=lang` flag missing. Would be nice to have a check there. But now that the windows open, I've got bitten by: https://github.com/alloy/macvim/issues/67

**Comment by alloy** [comment]
@b4winckler Thanks for chipping in on this one.
