### ISSUE TITLE
Please Provide OSX Binaries. Build Requires Full Install of Xcode

### ISSUE THREAD

**Issue by madranet** [alloy/macvim#92]
```
xcodebuild -project MacVim/MacVim.xcodeproj MACOSX_DEPLOYMENT_TARGET=10.11
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [macvim] Error 1
```

Since building this on OSX requires a full [6GB+ last time I looked] install of Xcode––the Xcode Command Line tools are not enough––it would be really helpful if you could provide some pre-built binaries for download. 

I'm sure I'm not alone in not wanting to download 6GB+ of bloated crap I'll never use,  just to build Vim with a nice GUI.

**Comment by kjyv** [comment]
I've added a binary release for the last version. Not that this is still version 7.4
